export default {
    0: "Daftar Tulisan",
    1: "YOKOSO",
    2: "Tsuaa ga hajimatta",
    3: "Sodachi sugite hana",
    4: "Babumi no aru Kurobe Damu",
    5: "Shinjū",
    6: "Zakki",
    7: "Pporo",
    8: "Sumiwataru yozora no yō na kodoku o",
    9: "Sanpo",
    10: "Umarekawattara mata jibun ni naritai?",
    11: "Shunrin",
    12: "Suki Kirai",
    13: "Bure mo Boyake mo Ato de Wakareba Ii",
    14: "Jūhassai",
    15: "Tsuiyaka kouen de yaru tame ni shinkyoku tsukutta yo",
    16: "Shigatsu kurabu haru yuurei ame",
    17: "Rurou no Tsuki",
    18: "Papparapaa",
    19: "Gumi Sengoku Jidai",
    20: "Kappu Nuudoru Kare Aji no Oishii Tabetakata",
    21: "Hana Ichi",
    22: "Hana Ni",
    23: "Tsuaa made mou sugu jan ne",
    24: "Jitsu wa",
    25: "Kimi o torimaku fushigi ga itsumademo tsuzukimasu you niーーーtte",
    26: "Tegami mitai na nikki",
    27: "Kinga Shinnen",
    28: "Kurosuwaado purezento kikaku no koto",
    29: "Tsuaa fainaru de totta shashin-tachi no kuyo",
    30: "Fukuoka no Omoide desu",
    31: "Nemureru You ni Natta",
    32: "Kaibutsu to Koten",
    33: "Jibun no Zeijakusei ga Kini Kawanai.",
    34: "AYATORI",
    35: "Puresosa",
    36: "Kaifuku",
    37: "Tōmei na ageha chō",
    38: "Tomarigi",
    39: "Shinsetsu",
    40: "Bonjin to Tensai",
    41: "Inu 3-sai",
    42: "Yurikago",
    43: "Hachigatsu da ne"
}